### ISSUE TITLE
Fixes for the style of the dropdown menu

### ISSUE THREAD

**Issue by nursandiid** [gonzaarcr/Fildem#140]
### Information

- **Ubuntu 21.10**:
- **Gnome Shell 40.5** 
- **X11**
- **Apps tested**:  
- **Fildem version 2**

I found a border like the following, maybe a little less good to look at
Can I find the css/style to be editable

![Screenshot from 2022-03-26 19-37-20](https://user-images.githubusercontent.com/47293812/160566711-e47b3720-4da8-4ed4-9e92-be07659b10c0.png)

**Comment by RoySRC** [comment]
Have you tried downloading the source and changing the `border-radius` in `set_custom_styles` function in `global_menu` module under the class `CommandWindow`. Here is the result:
![Screenshot from 2022-04-18 02-52-29](https://user-images.githubusercontent.com/12577420/163776647-9f0d0b07-05d0-4674-8876-4b52520f0505.png)

I think I have a working version [here](https://github.com/RoySRC/Fildem)

**Comment by nursandiid** [comment]
I have changed like that, border-radius: 3px and reinstall the fildem.deb
But for me it is not working

**Comment by RoySRC** [comment]
> I have changed like that, border-radius: 3px and reinstall the fildem.deb But for me it is not working

@sandinur157 I was wondering if you could try running through `python -m fildem.run` instead of first compiling to a deb package. I am a bit curious to see what running it this way gives you. You could just clone [this](git@github.com:RoySRC/Fildem.git) and run the command from inside the cloned directory.

Also, I forgot to mention that I am using wayland. I am not sure how much of an impact does that have.

**Comment by nursandiid** [comment]
@RoySRC 
Here's after i run command `python3 -m fildem.run`
![image](https://user-images.githubusercontent.com/47293812/163916283-733c5123-b3b6-47c9-bab2-4ed18eb68c39.png)

Here's my code after edited
![image](https://user-images.githubusercontent.com/47293812/163916514-68ba41db-e858-4648-920f-168bff8b0df1.png)

**Comment by RoySRC** [comment]
@sandinur157 here's my css:
```css
entry.search.flat { border: 0; outline: 0;
border-image: none; box-shadow: none; }

headerbar { box-shadow: none; background: @insensitive_bg_color;
border-radius: 0; border-width: 0 0 1px 0; }

scrolledwindow overshoot, scrolledwindow undershoot {
background: none; box-shadow: none; }

scrollbar { opacity: 0; }

menubar { background-color: #1d1d1d; }
menubar > menuitem { min-height: 1em; }

window decoration { box-shadow: none; border-color: @borders;
border-style: solid; border-width: 1px; border-radius: 12px; }
```

as you can see you need to change the `border-radius` under `window decoration` and use `python -m fildem.run` to test your changes. If everything works out, you can then issue `make build` to build a `.deb` file and install that.
